# Generated by Django 3.2.2 on 2021-05-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='images',
            name='Category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.category'),
        ),
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.location'),
        ),
    ]
