# Generated by Django 3.2.2 on 2021-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210517_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location']},
        ),
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
